name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dusk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, sqlite
          tools: composer, npm

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress

      - name: Copy .env
        run: cp .env.example .env

      - name: Configure SQLite database
        run: |
          touch /tmp/database.sqlite
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=\/tmp\/database.sqlite/' .env
          sed -i 's/APP_URL=.*/APP_URL=http:\/\/127.0.0.1:8000\nAPP_TESTING=true/' .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up Dusk environment
        run: |
          php artisan dusk:install
          php artisan dusk:chrome-driver --detect
          php artisan storage:link
          php artisan migrate --env=testing --force

      - name: Install npm dependencies and build assets
        run: |
          npm ci
          npm run build
        env:
          LARAVEL_BYPASS_ENV_CHECK: 1

      - name: Start Laravel server in background
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Laravel Dusk tests
        run: |
          cp .env .env.dusk.local
          php artisan dusk tests/Browser/GeneralTest.php
          php artisan dusk tests/Browser/TicketTest.php
        env:
          APP_ENV: local
          APP_URL: http://127.0.0.1:8000
  
      - name: Upload Dusk Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dusk-screenshots
          path: tests/Browser/screenshots